"""The edge layer's pinned sample receipt must satisfy the frozen LimitReceipt contract.

`edge/fixtures/limit-receipt.sample.json` is generated by the Workers edge layer
(`edge/scripts/regenerate-fixtures.mjs`) and byte-pinned by its own node test.
This test is the Python half of that pin: if the JavaScript shape and the
frozen dataclass drift apart, one of the two suites goes red. It reuses the
contract-freeze validator and its invariants, so the sample is held to exactly
the rules every fixture in tests/fixtures/contracts is held to.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest

from tests.test_contract_freeze import REPO_ROOT, validate_fixture

SAMPLE = Path(os.environ.get("NEWS_CURATOR_EDGE_SAMPLE", REPO_ROOT / "edge" / "fixtures" / "limit-receipt.sample.json"))


@pytest.mark.skipif(not SAMPLE.exists(), reason="edge layer not present in this tree")
def test_edge_sample_receipt_satisfies_the_frozen_limit_receipt_contract():
    payload = json.loads(SAMPLE.read_text(encoding="utf-8"))
    validate_fixture(
        {
            "contract": "receipt",
            "dataclass": "LimitReceipt",
            "expect": "valid",
            "note": "generated by the edge layer; pinned on both sides",
            "payload": payload,
        }
    )


@pytest.mark.skipif(not SAMPLE.exists(), reason="edge layer not present in this tree")
def test_edge_sample_receipt_carries_the_ownership_envelope():
    envelope = json.loads(SAMPLE.read_text(encoding="utf-8"))["envelope"]
    for key in ("tenant_id", "actor_id", "actor_kind", "user_id"):
        assert key in envelope, f"envelope lacks required ownership key {key}"
    assert envelope["kind"] == "host_limits"
