begin;

-- Session guards. The 28 generated ownership CHECK constraints below embed
-- regex escapes (\uXXXX / \UXXXXXXXX) inside PLAIN single-quoted literals,
-- which reach the regex engine as escapes only while
-- standard_conforming_strings is on (the Postgres default since 9.1). With
-- it off the same literal is parsed as an escape string and the leading NUL
-- escape is a string-literal error, so the migration would fail to apply.
-- The check text depends on this setting; do not remove the line.
--
-- ASSUMED RUNNER (round-6 should-fix): this guard protects the literals below
-- ONLY under a runner that sends statements one at a time (psql, and the
-- Supabase CLI's migration runner, which both split on `;`). Postgres's
-- simple Query protocol parses an ENTIRE multi-statement string into raw
-- parse trees, with string-literal escaping resolved at scan time, BEFORE
-- executing any statement in it; a runner that sends this whole file as one
-- string would parse all 28 literals before this SET takes effect, so the
-- guard would protect nothing in its own file under that runner. With the
-- setting off the literals fail LOUDLY (an invalid four-digit NUL escape)
-- rather than corrupting silently, so this is about the guard's honesty
-- under an unverified runner, not a corruption path.
set standard_conforming_strings = on;

-- Learning ledger: append-only behavioral history plus the durable records
-- that hang off it (evidence, artifacts, receipts). Modeled on the frozen
-- dataclasses in curator/contracts/{event,evidence,artifact,receipt,mirror,
-- tenant}.py. See docs/contracts/ledger-storage.md for the plain-English
-- summary of what this migration implements and what it deliberately does
-- not build yet.
--
-- Every table that stores a PRIVATE RECORD carries the same four ownership
-- columns, because the frozen dataclasses now inherit one shared Ownership
-- shape (curator/contracts/tenant.py):
--
--   tenant_id  text not null   the isolation boundary
--   actor_id   text not null   who wrote the row (no default: an empty
--                              actor_id used to be a column default, so an
--                              unattributed row was the default value)
--   actor_kind text not null   human | agent | system
--   user_id    text not null   the human the record is ABOUT
--
-- TWO-TIER SUBJECT ATTRIBUTION (2026-09-02). A record is SUBJECT-BOUND when a
-- "delete everything about me" request must be able to find it. All nine
-- tables below are subject-bound (behaviour, imports, artifacts, and the
-- receipts that prove their deletion), so user_id here is `not null` whatever
-- wrote the row: a system writer does not erase the human subject. The
-- `check (actor_kind = 'system' or user_id is not null)` form these tables
-- used to carry is gone; it let a normalizer-written row about one person
-- name nobody. Subjectless records (source checkpoints, plugin registry rows,
-- normalized public documents, pipeline intermediates) may carry a null
-- user_id and have no table here yet. The classification is frozen in
-- curator/contracts/__init__.py (SUBJECT_BOUND_RECORDS / SUBJECTLESS_RECORDS).
--
-- BLANK IS NOT NULL, AND NON-BLANK IS NOT CANONICAL. `not null`, `non-blank`
-- and `canonical` are three different rules, so every ownership column carries
-- all three clauses: equal to its own btrim, at least one non-space character,
-- and no invisible code point. Without the first, an empty actor_id (the exact
-- unattributed value this shape removed as a column default) and an empty
-- user_id were both legal and a deletion sweep filtering `user_id is null`
-- silently missed the blank rows. The old form was `btrim(x) <> ''`, and
-- btrim with no second argument strips SPACES ONLY: a live INSERT of a tab,
-- a newline, U+00A0 or U+3000 (one keystroke on a Chinese IME) was accepted by
-- the database while both Python validators rejected it. The invisible class
-- below is GENERATED by curator.ownership.ownership_id_sql_check from
-- INVISIBLE_ID_CODE_POINT_RANGES in curator/contracts/__init__.py; do not hand
-- edit it. A freeze test regenerates the text and fails on any drift.
--
-- FOURTH CLAUSE, `is nfc normalized` (2026-09-02). NFC and NFD spellings of
-- one visible id are two rows no reviewer can tell apart, so a per-person
-- delete keyed on the composed spelling misses the decomposed row. REQUIRES
-- PostgreSQL 13 or later on a UTF8 database; `IS NORMALIZED` is a core
-- predicate there and needs no extension. It is immutable, so it is legal
-- inside a CHECK. The Python half is curator.ownership.noncanonical_id_reason.
-- Unpaired surrogates are refused by the Python half only: a UTF8 database
-- cannot store one, so the write fails on encoding before any check runs.
--
-- KNOWN FAILURE MODE (round-6 should-fix, undiagnosed until now): Postgres
-- refuses a CHECK whose expression calls a non-IMMUTABLE function. If
-- `unicode_is_normalized` is not marked immutable on the target server, this
-- migration fails at the FIRST `create table` below, not at insert time. If a
-- live application of this file fails there, that is the diagnosis in one
-- line rather than a symptom to re-derive; it is not the astral escapes or
-- the widened invisible range, both of which are plain regex literals with no
-- such dependency.
--
-- Edited in place rather than superseded by a second migration: this file has
-- not been applied to any environment (grade B, the phase-4 slice records no
-- cloud mutation).
--
-- KNOWN OPEN, deferred with a corrected reason (2026-09-02): the four
-- `*_update_own` policies gate on tenant membership only, so any member may
-- `update ... set actor_id / actor_kind / user_id` after insert and rewrite the
-- attribution these columns exist to hold. The earlier stated blocker ("the
-- migration has an execution receipt") does not hold: that receipt covers a
-- scratch Postgres cluster, and the migration is presumed unapplied at grade C
-- because no live `schema_migrations` query has ever been run. A scratch
-- execution receipt is not an applied-state proof, so an in-place edit is
-- available. The item is SCHEDULED, not blocked.

-- ---------------------------------------------------------------------
-- Tenant membership: the predicate every RLS policy below is keyed on.
-- ---------------------------------------------------------------------

-- NAME COLLISION, resolved rather than papered over: this column holds an
-- AUTH PROVIDER SUBJECT (an auth.users uuid), while the contract's `user_id`
-- (curator/contracts/tenant.py: Ownership) is a stable, provider-neutral text
-- id that appears on every private record below. Two different things cannot
-- share one column name in the same schema, so the auth subject is `auth_uid`
-- here and `user_id` means the contract's value everywhere else.
--
-- Mapping one onto the other is the identity adapter's job (SC-32) and is
-- DEFERRED: no table below joins auth_uid to user_id yet, and nothing reads
-- user_id for authorization. Row isolation is keyed on tenant membership
-- alone, exactly as before.
create table public.tenant_members (
  tenant_id text not null,
  auth_uid uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default statement_timestamp(),
  primary key (tenant_id, auth_uid),
  -- Round 6: this was the ONE table in this migration carrying zero of the
  -- three canonical clauses the 27 (now 28) other ownership columns all
  -- carry. A membership row inserted with a stray trailing space would never
  -- equal the canonical tenant_id every owned table now REQUIRES, and
  -- is_tenant_member (below) compares by exact string equality, so that
  -- member would be silently denied select/insert on every table. Generated
  -- by the same curator.ownership.ownership_id_sql_check('tenant_id') as the
  -- rest; test_the_migration_ownership_checks_are_derived_from_the_frozen_set
  -- now asserts 28.
  check (tenant_id = btrim(tenant_id) and tenant_id ~ '[^[:space:]]' and tenant_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and tenant_id is nfc normalized)
);

alter table public.tenant_members enable row level security;
alter table public.tenant_members force row level security;

create policy tenant_members_select_own
on public.tenant_members for select
to authenticated
using (auth.uid() is not null and auth.uid() = auth_uid);

revoke all on table public.tenant_members from public, anon, authenticated;
grant select on table public.tenant_members to authenticated;

-- Exact `=` is correct here, not an approximation: both sides are canonical
-- BY CONSTRAINT. `m.tenant_id` carries the generated ownership_id_sql_check
-- above, and every caller of this function passes a `tenant_id` column that
-- carries the same check (see the per-table CHECK constraints below), so
-- neither side can be padded, carry an invisible code point, or sit in NFD.
-- Two canonical spellings of one tenant are the same string, which is what
-- makes exact string comparison sufficient rather than merely convenient.
create or replace function public.is_tenant_member(check_tenant_id text)
returns boolean
language sql
stable
security invoker
set search_path = pg_catalog, public
as $$
  select exists (
    select 1
    from public.tenant_members m
    where m.tenant_id = check_tenant_id and m.auth_uid = auth.uid()
  )
$$;

revoke execute on function public.is_tenant_member(text) from public, anon;
grant execute on function public.is_tenant_member(text) to authenticated;

-- ---------------------------------------------------------------------
-- Append-only enforcement: shared trigger function. Attached below to
-- learning_events, correction_events, evidence_items, artifact_versions.
-- Blocks UPDATE and DELETE for every role, including service_role, since a
-- trigger fires regardless of RLS or grants. Retraction is a new row in
-- correction_events, never an edit to the row being retracted.
-- ---------------------------------------------------------------------

create or replace function public.reject_ledger_mutation()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  raise exception using
    errcode = '0A000',
    message = format(
      'append-only table %I: %s is not permitted; write a new row instead',
      TG_TABLE_NAME, TG_OP
    );
end;
$$;

revoke execute on function public.reject_ledger_mutation() from public, anon, authenticated;

-- ---------------------------------------------------------------------
-- learning_events (curator/contracts/event.py: LearningEvent)
-- ---------------------------------------------------------------------

create table public.learning_events (
  event_id text primary key,
  tenant_id text not null,
  actor_id text not null,
  actor_kind text not null check (actor_kind in ('human', 'agent', 'system')),
  user_id text not null,
  event_type text not null check (event_type in (
    'more_like_this', 'less_like_this', 'already_knew_this', 'surprise_me',
    'save', 'save_answer', 'ask_ai_question', 'ask_ai_follow_up',
    'create_report', 'read_more', 'accordion_expand', 'return_to_story',
    'dwell', 'scroll', 'imported_mail_unread_state', 'imported_browser_visit'
  )),
  occurred_at timestamptz not null,
  recorded_at timestamptz not null,
  surface text not null,
  idempotency_key text not null,
  evidence_class text not null check (evidence_class in ('observed', 'inferred', 'explicit', 'passive')),
  origin text not null check (origin in ('live', 'imported')),
  confidence text not null check (confidence in ('strong', 'medium', 'weak')),
  policy_revision integer not null,
  story_id text,
  story_cluster_id text,
  artifact_id text,
  conversation_id text,
  session_id text not null default '',
  duration_ms integer,
  retracted_by_event_id text,
  -- (tenant_id, user_id, idempotency_key), decided 2026-09-02: a tenant-scoped
  -- key alone let a same-tenant collision on the same key TEXT but a
  -- different user_id silently return the OTHER user's row (see
  -- docs/contracts/event.md and curator/ledger/memory.py, which key the
  -- in-memory index the same way so the two surfaces cannot drift).
  unique (tenant_id, user_id, idempotency_key),
  check (tenant_id = btrim(tenant_id) and tenant_id ~ '[^[:space:]]' and tenant_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and tenant_id is nfc normalized),
  check (actor_id = btrim(actor_id) and actor_id ~ '[^[:space:]]' and actor_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and actor_id is nfc normalized),
  check (user_id = btrim(user_id) and user_id ~ '[^[:space:]]' and user_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and user_id is nfc normalized)
);

alter table public.learning_events enable row level security;
alter table public.learning_events force row level security;

create policy learning_events_select_own
on public.learning_events for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy learning_events_insert_own
on public.learning_events for insert
to authenticated
with check (public.is_tenant_member(tenant_id));

create trigger learning_events_append_only
before update or delete on public.learning_events
for each row execute function public.reject_ledger_mutation();

revoke all on table public.learning_events from public, anon, authenticated;
revoke update, delete on table public.learning_events from authenticated;
grant select, insert on table public.learning_events to authenticated;

-- ---------------------------------------------------------------------
-- correction_events (curator/contracts/event.py: CorrectionEvent)
-- ---------------------------------------------------------------------

create table public.correction_events (
  event_id text primary key,
  tenant_id text not null,
  actor_id text not null,
  actor_kind text not null check (actor_kind in ('human', 'agent', 'system')),
  user_id text not null,
  action text not null check (action in ('correct', 'retract', 'delete_request')),
  target_kind text not null,
  target_id text not null,
  reason_code text not null,
  occurred_at timestamptz not null,
  invalidated_snapshot_ids text[] not null default '{}'::text[],
  check (tenant_id = btrim(tenant_id) and tenant_id ~ '[^[:space:]]' and tenant_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and tenant_id is nfc normalized),
  check (actor_id = btrim(actor_id) and actor_id ~ '[^[:space:]]' and actor_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and actor_id is nfc normalized),
  check (user_id = btrim(user_id) and user_id ~ '[^[:space:]]' and user_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and user_id is nfc normalized)
);

alter table public.correction_events enable row level security;
alter table public.correction_events force row level security;

create policy correction_events_select_own
on public.correction_events for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy correction_events_insert_own
on public.correction_events for insert
to authenticated
with check (public.is_tenant_member(tenant_id));

create trigger correction_events_append_only
before update or delete on public.correction_events
for each row execute function public.reject_ledger_mutation();

revoke all on table public.correction_events from public, anon, authenticated;
revoke update, delete on table public.correction_events from authenticated;
grant select, insert on table public.correction_events to authenticated;

-- ---------------------------------------------------------------------
-- raw_imports (curator/contracts/evidence.py: RawImport)
-- ---------------------------------------------------------------------

create table public.raw_imports (
  raw_import_id text primary key,
  tenant_id text not null,
  actor_id text not null,
  actor_kind text not null check (actor_kind in ('human', 'agent', 'system')),
  user_id text not null,
  source_kind text not null,
  checksum text not null,
  schema_version text not null,
  storage_reference text not null,
  imported_at timestamptz not null,
  consent_version text not null,
  retention_state text not null check (retention_state in ('active', 'retracted', 'purged')),
  exported_at timestamptz,
  byte_size integer not null default 0,
  unique (tenant_id, source_kind, checksum),
  check (tenant_id = btrim(tenant_id) and tenant_id ~ '[^[:space:]]' and tenant_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and tenant_id is nfc normalized),
  check (actor_id = btrim(actor_id) and actor_id ~ '[^[:space:]]' and actor_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and actor_id is nfc normalized),
  check (user_id = btrim(user_id) and user_id ~ '[^[:space:]]' and user_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and user_id is nfc normalized),
  -- Redundant with the primary key on its own, and required as the TARGET of
  -- evidence_items' composite tenant foreign key below.
  unique (raw_import_id, tenant_id)
);

alter table public.raw_imports enable row level security;
alter table public.raw_imports force row level security;

create policy raw_imports_select_own
on public.raw_imports for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy raw_imports_insert_own
on public.raw_imports for insert
to authenticated
with check (public.is_tenant_member(tenant_id));

create policy raw_imports_update_own
on public.raw_imports for update
to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

revoke all on table public.raw_imports from public, anon, authenticated;
grant select, insert, update on table public.raw_imports to authenticated;

-- ---------------------------------------------------------------------
-- evidence_items (curator/contracts/evidence.py: EvidenceItem)
-- ---------------------------------------------------------------------

create table public.evidence_items (
  evidence_id text primary key,
  tenant_id text not null,
  actor_id text not null,
  actor_kind text not null check (actor_kind in ('human', 'agent', 'system')),
  user_id text not null,
  raw_import_id text,
  source_item_id text not null,
  occurred_at timestamptz not null,
  recorded_at timestamptz not null,
  evidence_class text not null check (evidence_class in ('observed', 'inferred', 'explicit', 'passive')),
  origin text not null check (origin in ('live', 'imported')),
  confidence text not null check (confidence in ('strong', 'medium', 'weak')),
  weight double precision not null,
  policy_revision integer not null,
  story_id text,
  canonical_url text not null default '',
  entity_ids text[] not null default '{}'::text[],
  topic_tags text[] not null default '{}'::text[],
  corroborated boolean not null default false,
  corroborating_evidence_ids text[] not null default '{}'::text[],
  retracted_by_event_id text,
  check (tenant_id = btrim(tenant_id) and tenant_id ~ '[^[:space:]]' and tenant_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and tenant_id is nfc normalized),
  check (actor_id = btrim(actor_id) and actor_id ~ '[^[:space:]]' and actor_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and actor_id is nfc normalized),
  check (user_id = btrim(user_id) and user_id ~ '[^[:space:]]' and user_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and user_id is nfc normalized),
  -- Composite, so an evidence item cannot name an import that belongs to a
  -- different tenant. Referential integrity is checked with row security OFF,
  -- so RLS does not stop a tenant-A member inserting a child whose parent is
  -- in tenant B; only the tenant column in the key does.
  --
  -- raw_import_id is NULLABLE and this FK is MATCH SIMPLE (the default), so a
  -- row with a null raw_import_id skips the constraint entirely. That is the
  -- intended behaviour: live evidence has no import to point at. tenant_id is
  -- `not null` on this table, so the half-null case that MATCH SIMPLE would
  -- also skip cannot arise from the tenant side.
  foreign key (raw_import_id, tenant_id)
    references public.raw_imports (raw_import_id, tenant_id)
);

alter table public.evidence_items enable row level security;
alter table public.evidence_items force row level security;

create policy evidence_items_select_own
on public.evidence_items for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy evidence_items_insert_own
on public.evidence_items for insert
to authenticated
with check (public.is_tenant_member(tenant_id));

create trigger evidence_items_append_only
before update or delete on public.evidence_items
for each row execute function public.reject_ledger_mutation();

revoke all on table public.evidence_items from public, anon, authenticated;
revoke update, delete on table public.evidence_items from authenticated;
grant select, insert on table public.evidence_items to authenticated;

-- ---------------------------------------------------------------------
-- knowledge_artifacts (curator/contracts/artifact.py: KnowledgeArtifact)
-- ---------------------------------------------------------------------

create table public.knowledge_artifacts (
  artifact_id text primary key,
  tenant_id text not null,
  actor_id text not null,
  actor_kind text not null check (actor_kind in ('human', 'agent', 'system')),
  user_id text not null,
  artifact_type text not null check (artifact_type in ('question', 'answer', 'report', 'insight', 'save')),
  status text not null check (status in ('draft', 'settled', 'redacted', 'retracted')),
  publication_class text not null check (publication_class in ('private', 'public')),
  created_at timestamptz not null,
  current_version integer not null,
  title text not null default '',
  conversation_id text,
  story_id text,
  check (tenant_id = btrim(tenant_id) and tenant_id ~ '[^[:space:]]' and tenant_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and tenant_id is nfc normalized),
  check (actor_id = btrim(actor_id) and actor_id ~ '[^[:space:]]' and actor_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and actor_id is nfc normalized),
  check (user_id = btrim(user_id) and user_id ~ '[^[:space:]]' and user_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and user_id is nfc normalized),
  -- artifact_id is already the primary key; this redundant unique key is what
  -- lets artifact_versions carry a COMPOSITE foreign key on
  -- (artifact_id, tenant_id), so a version can never claim a tenant its
  -- parent artifact does not have.
  unique (artifact_id, tenant_id)
);

alter table public.knowledge_artifacts enable row level security;
alter table public.knowledge_artifacts force row level security;

create policy knowledge_artifacts_select_own
on public.knowledge_artifacts for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy knowledge_artifacts_insert_own
on public.knowledge_artifacts for insert
to authenticated
with check (public.is_tenant_member(tenant_id));

create policy knowledge_artifacts_update_own
on public.knowledge_artifacts for update
to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

revoke all on table public.knowledge_artifacts from public, anon, authenticated;
grant select, insert, update on table public.knowledge_artifacts to authenticated;

-- ---------------------------------------------------------------------
-- artifact_versions (curator/contracts/artifact.py: ArtifactVersion)
-- Carries its own tenant_id since 2026-09-02: it used to prove tenancy ONLY
-- through a join to its parent artifact. The composite foreign key on
-- (artifact_id, tenant_id) is what keeps the two from disagreeing, so a
-- version cannot name a different tenant than the artifact it belongs to.
-- ---------------------------------------------------------------------

create table public.artifact_versions (
  artifact_id text not null,
  tenant_id text not null,
  actor_id text not null,
  actor_kind text not null check (actor_kind in ('human', 'agent', 'system')),
  user_id text not null,
  version integer not null,
  parent_version integer,
  checksum text not null,
  content_reference text not null,
  settled_at timestamptz not null,
  citations text[] not null default '{}'::text[],
  redacted_by_event_id text,
  primary key (artifact_id, version),
  check (tenant_id = btrim(tenant_id) and tenant_id ~ '[^[:space:]]' and tenant_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and tenant_id is nfc normalized),
  check (actor_id = btrim(actor_id) and actor_id ~ '[^[:space:]]' and actor_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and actor_id is nfc normalized),
  check (user_id = btrim(user_id) and user_id ~ '[^[:space:]]' and user_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and user_id is nfc normalized),
  foreign key (artifact_id, tenant_id)
    references public.knowledge_artifacts (artifact_id, tenant_id)
);

alter table public.artifact_versions enable row level security;
alter table public.artifact_versions force row level security;

-- Both halves are required, deliberately. The parent join is the historical
-- check; the direct is_tenant_member(tenant_id) is what makes the row's own
-- tenant column load-bearing rather than decorative.
create policy artifact_versions_select_own
on public.artifact_versions for select
to authenticated
using (
  public.is_tenant_member(tenant_id)
  and exists (
    select 1 from public.knowledge_artifacts ka
    where ka.artifact_id = artifact_versions.artifact_id
      and public.is_tenant_member(ka.tenant_id)
  )
);

create policy artifact_versions_insert_own
on public.artifact_versions for insert
to authenticated
with check (
  public.is_tenant_member(tenant_id)
  and exists (
    select 1 from public.knowledge_artifacts ka
    where ka.artifact_id = artifact_versions.artifact_id
      and public.is_tenant_member(ka.tenant_id)
  )
);

create trigger artifact_versions_append_only
before update or delete on public.artifact_versions
for each row execute function public.reject_ledger_mutation();

revoke all on table public.artifact_versions from public, anon, authenticated;
revoke update, delete on table public.artifact_versions from authenticated;
grant select, insert on table public.artifact_versions to authenticated;

-- ---------------------------------------------------------------------
-- artifact_relations (curator/contracts/artifact.py: ArtifactRelation)
-- ---------------------------------------------------------------------

create table public.artifact_relations (
  relation_id text primary key,
  tenant_id text not null,
  actor_id text not null,
  actor_kind text not null check (actor_kind in ('human', 'agent', 'system')),
  user_id text not null,
  conversation_id text not null,
  artifact_id text not null,
  relation_type text not null,
  requested_type text not null default '',
  depth integer not null default 0,
  check (tenant_id = btrim(tenant_id) and tenant_id ~ '[^[:space:]]' and tenant_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and tenant_id is nfc normalized),
  check (actor_id = btrim(actor_id) and actor_id ~ '[^[:space:]]' and actor_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and actor_id is nfc normalized),
  check (user_id = btrim(user_id) and user_id ~ '[^[:space:]]' and user_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and user_id is nfc normalized),
  -- Composite, so a child cannot name a parent artifact in a different
  -- tenant. Referential integrity is checked with row security OFF, so RLS
  -- does not stop a tenant-A member inserting a child whose parent is in
  -- tenant B; only the tenant column in the key does.
  foreign key (artifact_id, tenant_id)
    references public.knowledge_artifacts (artifact_id, tenant_id)
);

alter table public.artifact_relations enable row level security;
alter table public.artifact_relations force row level security;

create policy artifact_relations_select_own
on public.artifact_relations for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy artifact_relations_insert_own
on public.artifact_relations for insert
to authenticated
with check (public.is_tenant_member(tenant_id));

revoke all on table public.artifact_relations from public, anon, authenticated;
grant select, insert on table public.artifact_relations to authenticated;

-- ---------------------------------------------------------------------
-- deletion_receipts (curator/contracts/receipt.py: ReceiptEnvelope + DeletionReceipt)
-- ---------------------------------------------------------------------

create or replace function public.deletion_receipt_may_settle(state text, projections jsonb)
returns boolean
language sql
immutable
set search_path = pg_catalog
as $$
  select state <> 'settled'
    or not exists (
      select 1
      from jsonb_array_elements(projections) as p
      where (p ->> 'resolved') is distinct from 'true'
    )
$$;

revoke execute on function public.deletion_receipt_may_settle(text, jsonb) from public, anon, authenticated;

create table public.deletion_receipts (
  receipt_id text primary key,
  tenant_id text not null,
  kind text not null default 'deletion',
  state text not null check (state in ('settled', 'partial', 'failed', 'unknown')),
  created_at timestamptz not null,
  policy_revision integer not null,
  -- No default. An unattributed receipt used to be this column's own default
  -- value, so a writer that never set it produced a receipt naming nobody.
  actor_id text not null,
  actor_kind text not null check (actor_kind in ('human', 'agent', 'system')),
  user_id text not null,
  reason_code text not null default '',
  settled_at timestamptz,
  target_kind text not null,
  target_ids text[] not null default '{}'::text[],
  correction_watermark timestamptz not null,
  invalidated_snapshot_ids text[] not null default '{}'::text[],
  rebuild_id text not null,
  zero_contribution_verdict boolean not null,
  projections jsonb not null default '[]'::jsonb check (jsonb_typeof(projections) = 'array'),
  mirrored_targets text[] not null default '{}'::text[],
  audit_chain_queryable boolean not null default true,
  check (public.deletion_receipt_may_settle(state, projections)),
  check (tenant_id = btrim(tenant_id) and tenant_id ~ '[^[:space:]]' and tenant_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and tenant_id is nfc normalized),
  check (actor_id = btrim(actor_id) and actor_id ~ '[^[:space:]]' and actor_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and actor_id is nfc normalized),
  check (user_id = btrim(user_id) and user_id ~ '[^[:space:]]' and user_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and user_id is nfc normalized)
);

alter table public.deletion_receipts enable row level security;
alter table public.deletion_receipts force row level security;

create policy deletion_receipts_select_own
on public.deletion_receipts for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy deletion_receipts_insert_own
on public.deletion_receipts for insert
to authenticated
with check (public.is_tenant_member(tenant_id));

create policy deletion_receipts_update_own
on public.deletion_receipts for update
to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

revoke all on table public.deletion_receipts from public, anon, authenticated;
grant select, insert, update on table public.deletion_receipts to authenticated;

-- ---------------------------------------------------------------------
-- mirror_receipts (curator/contracts/mirror.py: MirrorReceipt)
-- ---------------------------------------------------------------------

create table public.mirror_receipts (
  receipt_id text primary key,
  tenant_id text not null,
  actor_id text not null,
  actor_kind text not null check (actor_kind in ('human', 'agent', 'system')),
  user_id text not null,
  artifact_id text not null,
  artifact_version integer not null,
  adapter_id text not null,
  target_id text not null,
  state text not null check (state in ('planned', 'writing', 'settled', 'conflict', 'unknown')),
  idempotency_key text not null,
  attempted_at timestamptz not null,
  expected_prior_checksum text not null,
  attempted_checksum text not null,
  readback_checksum text not null default '',
  settled_at timestamptz,
  reason_code text not null default '',
  created_revision_id text not null default '',
  prior_receipt_ids text[] not null default '{}'::text[],
  prior_attempt_state text not null default '',
  resolution_ref text not null default '',
  -- Same key text may be reused by different users in one tenant. Replaying
  -- the same user's key is the duplicate this receipt identity refuses.
  constraint mirror_receipts_tenant_user_idempotency_key_key
    unique (tenant_id, user_id, idempotency_key),
  check (tenant_id = btrim(tenant_id) and tenant_id ~ '[^[:space:]]' and tenant_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and tenant_id is nfc normalized),
  check (actor_id = btrim(actor_id) and actor_id ~ '[^[:space:]]' and actor_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and actor_id is nfc normalized),
  check (user_id = btrim(user_id) and user_id ~ '[^[:space:]]' and user_id !~ '[\u0000-\u0020\u007F-\u00A0\u00AD\u0600-\u0605\u061C\u06DD\u070F\u0890-\u0891\u08E2\u1680\u180E\u2000-\u200F\u2028-\u202F\u205F-\u2064\u2066-\u206F\u3000\uFEFF\uFFF9-\uFFFB\U000110BD\U000110CD\U00013430-\U00013438\U0001BCA0-\U0001BCA3\U0001D173-\U0001D17A\U000E0001\U000E0020-\U000E007F]' and user_id is nfc normalized),
  -- Composite, so a child cannot name a parent artifact in a different
  -- tenant. Referential integrity is checked with row security OFF, so RLS
  -- does not stop a tenant-A member inserting a child whose parent is in
  -- tenant B; only the tenant column in the key does.
  foreign key (artifact_id, tenant_id)
    references public.knowledge_artifacts (artifact_id, tenant_id)
);

alter table public.mirror_receipts enable row level security;
alter table public.mirror_receipts force row level security;

create policy mirror_receipts_select_own
on public.mirror_receipts for select
to authenticated
using (public.is_tenant_member(tenant_id));

create policy mirror_receipts_insert_own
on public.mirror_receipts for insert
to authenticated
with check (public.is_tenant_member(tenant_id));

create policy mirror_receipts_update_own
on public.mirror_receipts for update
to authenticated
using (public.is_tenant_member(tenant_id))
with check (public.is_tenant_member(tenant_id));

revoke all on table public.mirror_receipts from public, anon, authenticated;
grant select, insert, update on table public.mirror_receipts to authenticated;

commit;
